{% set name = "psycogreen" %}
{% set version = "1.0.2" %}
{% set sha256 = "c429845a8a49cf2f76b71265008760bcd7c7c77d80b806db4dc81116dbcd130d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - psycogreen

about:
  home: https://bitbucket.org/dvarrazzo/psycogreen
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'psycopg2 integration with coroutine libraries'
  description: |
    The psycogreen package enables psycopg2 to work with coroutine libraries, using asynchronous
    calls internally but offering a blocking interface so that regular code can run unmodified.
  doc_url: https://bitbucket.org/dvarrazzo/psycogreen
  dev_url: https://bitbucket.org/dvarrazzo/psycogreen

extra:
  recipe-maintainers:
    - petercable
